[tasks.ci]
description = "Build and smoke test the Docker image"
run = """
  set -e
  docker build --tag neovim-container:ci .
  trap 'docker image rm neovim-container:ci' EXIT
  docker run --rm --entrypoint test neovim-container:ci -s /etc/ssl/certs/ca-certificates.crt
  docker run --rm neovim-container:ci --headless '+qa'
  docker run --rm --entrypoint git neovim-container:ci --version
  docker run --rm --entrypoint rg neovim-container:ci --version
  docker run --rm --entrypoint sh neovim-container:ci -eu -c '
    parsers="
      bash capnp cmake cpp css csv dart dockerfile gitcommit haskell html
      javascript json json5 just luadoc make python regex rust toml tsx
      typescript yaml
      c diff lua markdown markdown_inline vimscript vimdoc
    "
    for parser in ${parsers}; do
      nvim --headless -u NONE \
        -c "lua assert(vim.treesitter.language.add('${parser}'))" \
        -c "qa"
    done
  '
  echo "CI completed successfully."
"""
